module.exports = {
  '/health': require('./health'),
  '/api/status': require('./status'),
  '/api/data/summary': require('./data_summary'),
  '/api/analytics': require('./analytics'),
  '/api/auth/status': require('./auth'),
  '/api/backtest': require('./backtest'),
  '/api/correlation': require('./correlation'),
  '/api/database/status': require('./database'),
  '/api/backend/stats': require('./stats'),
  '/api/backend/portfolio': require('./portfolio'),
  '/api/universe': require('./universe'),
  '/api/cache/universe': require('./universe'),
  '/api/indicators': require('./indicators'),
  '/api/quotes/status': require('./quotes'),
  '/api/cache/list': require('./cache_list'),
  '/api/signal': require('./signal'),
  '/api/signal/promote': require('./signal_promote'),
  '/api/supabase/config': require('./supabase_config'),
  '/api/system/status': require('./system'),
  '/api/kill-switch': require('./kill_switch'),
  '/api/strategies': require('./strategies'),
  '/api/config': require('./config'),
  '/api/sigma-band':  require('./sigma_band'),
  '/api/bot/status':  require('./bot_status'),
  '/api/bot/cycle':   require('./bot_cycle'),
  '/api/bot/sell':    require('./bot_sell'),
};
